
export interface DatabaseCollege {
  name: string;
  division: string;
  location: string;
}

export const COLLEGE_DATABASE: DatabaseCollege[] = [
  // NCAA D1
  { name: 'Abilene Christian University', division: 'NCAA D1', location: 'Abilene, TX' },
  { name: 'Air Force Academy', division: 'NCAA D1', location: 'USAFA, CO' },
  { name: 'University of Akron', division: 'NCAA D1', location: 'Akron, OH' },
  { name: 'University of Alabama', division: 'NCAA D1', location: 'Tuscaloosa, AL' },
  { name: 'Alabama A&M University', division: 'NCAA D1', location: 'Normal, AL' },
  { name: 'Alabama State University', division: 'NCAA D1', location: 'Montgomery, AL' },
  { name: 'University of Albany', division: 'NCAA D1', location: 'Albany, NY' },
  { name: 'Alcorn State University', division: 'NCAA D1', location: 'Lorman, MS' },
  { name: 'American University', division: 'NCAA D1', location: 'Washington, DC' },
  { name: 'Appalachian State University', division: 'NCAA D1', location: 'Boone, NC' },
  { name: 'University of Arizona', division: 'NCAA D1', location: 'Tucson, AZ' },
  { name: 'Arizona State University', division: 'NCAA D1', location: 'Tempe, AZ' },
  { name: 'University of Arkansas', division: 'NCAA D1', location: 'Fayetteville, AR' },
  { name: 'Arkansas State University', division: 'NCAA D1', location: 'Jonesboro, AR' },
  { name: 'Auburn University', division: 'NCAA D1', location: 'Auburn, AL' },
  { name: 'Baylor University', division: 'NCAA D1', location: 'Waco, TX' },
  { name: 'Boise State University', division: 'NCAA D1', location: 'Boise, ID' },
  { name: 'Boston College', division: 'NCAA D1', location: 'Chestnut Hill, MA' },
  { name: 'Boston University', division: 'NCAA D1', location: 'Boston, MA' },
  { name: 'Brigham Young University', division: 'NCAA D1', location: 'Provo, UT' },
  { name: 'University of California, Berkeley', division: 'NCAA D1', location: 'Berkeley, CA' },
  { name: 'University of California, Los Angeles', division: 'NCAA D1', location: 'Los Angeles, CA' },
  { name: 'Clemson University', division: 'NCAA D1', location: 'Clemson, SC' },
  { name: 'University of Colorado Boulder', division: 'NCAA D1', location: 'Boulder, CO' },
  { name: 'Duke University', division: 'NCAA D1', location: 'Durham, NC' },
  { name: 'University of Florida', division: 'NCAA D1', location: 'Gainesville, FL' },
  { name: 'Florida State University', division: 'NCAA D1', location: 'Tallahassee, FL' },
  { name: 'University of Georgia', division: 'NCAA D1', location: 'Athens, GA' },
  { name: 'Georgia Tech', division: 'NCAA D1', location: 'Atlanta, GA' },
  { name: 'Harvard University', division: 'NCAA D1', location: 'Cambridge, MA' },
  { name: 'University of Houston', division: 'NCAA D1', location: 'Houston, TX' },
  { name: 'University of Illinois', division: 'NCAA D1', location: 'Champaign, IL' },
  { name: 'Indiana University', division: 'NCAA D1', location: 'Bloomington, IN' },
  { name: 'University of Iowa', division: 'NCAA D1', location: 'Iowa City, IA' },
  { name: 'Kansas State University', division: 'NCAA D1', location: 'Manhattan, KS' },
  { name: 'University of Kansas', division: 'NCAA D1', location: 'Lawrence, KS' },
  { name: 'University of Kentucky', division: 'NCAA D1', location: 'Lexington, KY' },
  { name: 'Louisiana State University', division: 'NCAA D1', location: 'Baton Rouge, LSU' },
  { name: 'University of Maryland', division: 'NCAA D1', location: 'College Park, MD' },
  { name: 'University of Miami', division: 'NCAA D1', location: 'Coral Gables, FL' },
  { name: 'University of Michigan', division: 'NCAA D1', location: 'Ann Arbor, MI' },
  { name: 'Michigan State University', division: 'NCAA D1', location: 'East Lansing, MI' },
  { name: 'University of Minnesota', division: 'NCAA D1', location: 'Minneapolis, MN' },
  { name: 'Mississippi State University', division: 'NCAA D1', location: 'Starkville, MS' },
  { name: 'University of Mississippi', division: 'NCAA D1', location: 'Oxford, MS' },
  { name: 'University of Missouri', division: 'NCAA D1', location: 'Columbia, MO' },
  { name: 'University of Nebraska-Lincoln', division: 'NCAA D1', location: 'Lincoln, NE' },
  { name: 'University of North Carolina at Chapel Hill', division: 'NCAA D1', location: 'Chapel Hill, NC' },
  { name: 'North Carolina State University', division: 'NCAA D1', location: 'Raleigh, NC' },
  { name: 'Northwestern University', division: 'NCAA D1', location: 'Evanston, IL' },
  { name: 'University of Notre Dame', division: 'NCAA D1', location: 'Notre Dame, IN' },
  { name: 'Ohio State University', division: 'NCAA D1', location: 'Columbus, OH' },
  { name: 'University of Oklahoma', division: 'NCAA D1', location: 'Norman, OK' },
  { name: 'Oklahoma State University', division: 'NCAA D1', location: 'Stillwater, OK' },
  { name: 'University of Oregon', division: 'NCAA D1', location: 'Eugene, OR' },
  { name: 'Oregon State University', division: 'NCAA D1', location: 'Corvallis, OR' },
  { name: 'Pennsylvania State University', division: 'NCAA D1', location: 'University Park, PA' },
  { name: 'University of Pittsburgh', division: 'NCAA D1', location: 'Pittsburgh, PA' },
  { name: 'Purdue University', division: 'NCAA D1', location: 'West Lafayette, IN' },
  { name: 'Rice University', division: 'NCAA D1', location: 'Houston, TX' },
  { name: 'Rutgers University', division: 'NCAA D1', location: 'New Brunswick, NJ' },
  { name: 'University of South Carolina', division: 'NCAA D1', location: 'Columbia, SC' },
  { name: 'University of Southern California', division: 'NCAA D1', location: 'Los Angeles, CA' },
  { name: 'Stanford University', division: 'NCAA D1', location: 'Stanford, CA' },
  { name: 'Syracuse University', division: 'NCAA D1', location: 'Syracuse, NY' },
  { name: 'Texas A&M University', division: 'NCAA D1', location: 'College Station, TX' },
  { name: 'University of Texas at Austin', division: 'NCAA D1', location: 'Austin, TX' },
  { name: 'Texas Christian University', division: 'NCAA D1', location: 'Fort Worth, TX' },
  { name: 'Texas Tech University', division: 'NCAA D1', location: 'Lubbock, TX' },
  { name: 'University of Utah', division: 'NCAA D1', location: 'Salt Lake City, UT' },
  { name: 'Vanderbilt University', division: 'NCAA D1', location: 'Nashville, TN' },
  { name: 'University of Virginia', division: 'NCAA D1', location: 'Charlottesville, VA' },
  { name: 'Virginia Tech', division: 'NCAA D1', location: 'Blacksburg, VA' },
  { name: 'University of Washington', division: 'NCAA D1', location: 'Seattle, WA' },
  { name: 'Washington State University', division: 'NCAA D1', location: 'Pullman, WA' },
  { name: 'West Virginia University', division: 'NCAA D1', location: 'Morgantown, WV' },
  { name: 'University of Wisconsin-Madison', division: 'NCAA D1', location: 'Madison, WI' },
  { name: 'Yale University', division: 'NCAA D1', location: 'New Haven, CT' },

  // NCAA D2
  { name: 'Academy of Art University', division: 'NCAA D2', location: 'San Francisco, CA' },
  { name: 'Adams State University', division: 'NCAA D2', location: 'Alamosa, CO' },
  { name: 'Adelphi University', division: 'NCAA D2', location: 'Garden City, NY' },
  { name: 'University of Alabama in Huntsville', division: 'NCAA D2', location: 'Huntsville, AL' },
  { name: 'Albany State University', division: 'NCAA D2', location: 'Albany, GA' },
  { name: 'Angelo State University', division: 'NCAA D2', location: 'San Angelo, TX' },
  { name: 'Augustana University', division: 'NCAA D2', location: 'Sioux Falls, SD' },
  { name: 'Azusa Pacific University', division: 'NCAA D2', location: 'Azusa, CA' },
  { name: 'Barry University', division: 'NCAA D2', location: 'Miami Shores, FL' },
  { name: 'Bentley University', division: 'NCAA D2', location: 'Waltham, MA' },
  { name: 'California State University, Chico', division: 'NCAA D2', location: 'Chico, CA' },
  { name: 'Colorado School of Mines', division: 'NCAA D2', location: 'Golden, CO' },
  { name: 'Grand Valley State University', division: 'NCAA D2', location: 'Allendale, MI' },

  // NCAA D3
  { name: 'Adrian College', division: 'NCAA D3', location: 'Adrian, MI' },
  { name: 'Amherst College', division: 'NCAA D3', location: 'Amherst, MA' },
  { name: 'Bowdoin College', division: 'NCAA D3', location: 'Brunswick, ME' },
  { name: 'Carnegie Mellon University', division: 'NCAA D3', location: 'Pittsburgh, PA' },
  { name: 'Case Western Reserve University', division: 'NCAA D3', location: 'Cleveland, OH' },
  { name: 'University of Chicago', division: 'NCAA D3', location: 'Chicago, IL' },
  { name: 'Emory University', division: 'NCAA D3', location: 'Atlanta, GA' },
  { name: 'Johns Hopkins University', division: 'NCAA D3', location: 'Baltimore, MD' },
  { name: 'Middlebury College', division: 'NCAA D3', location: 'Middlebury, VT' },
  { name: 'Pomona College', division: 'NCAA D3', location: 'Claremont, CA' },
  { name: 'Tufts University', division: 'NCAA D3', location: 'Medford, MA' },
  { name: 'Washington University in St. Louis', division: 'NCAA D3', location: 'St. Louis, MO' },
  { name: 'Williams College', division: 'NCAA D3', location: 'Williamstown, MA' },

  // NAIA
  { name: 'Baker University', division: 'NAIA', location: 'Baldwin City, KS' },
  { name: 'Benedictine College', division: 'NAIA', location: 'Atchison, KS' },
  { name: 'Carroll College', division: 'NAIA', location: 'Helena, MT' },
  { name: 'College of Idaho', division: 'NAIA', location: 'Caldwell, ID' },
  { name: 'Concordia University Ann Arbor', division: 'NAIA', location: 'Ann Arbor, MI' },
  { name: 'Dordt University', division: 'NAIA', location: 'Sioux Center, IA' },
  { name: 'Georgetown College', division: 'NAIA', location: 'Georgetown, KY' },
  { name: 'Grand View University', division: 'NAIA', location: 'Des Moines, IA' },
  { name: 'Indiana Wesleyan University', division: 'NAIA', location: 'Marion, IN' },
  { name: 'Keiser University', division: 'NAIA', location: 'West Palm Beach, FL' },
  { name: 'Marian University', division: 'NAIA', location: 'Indianapolis, IN' },
  { name: 'Morningside University', division: 'NAIA', location: 'Sioux City, IA' },
  { name: 'Northwestern College', division: 'NAIA', location: 'Orange City, IA' },
  { name: 'Southeastern University', division: 'NAIA', location: 'Lakeland, FL' },

  // NJCAA / Community Colleges (CCCCO)
  { name: 'Foothill College', division: 'NJCAA', location: 'Los Altos Hills, CA' },
  { name: 'Fresno City College', division: 'NJCAA', location: 'Fresno, CA' },
  { name: 'Fullerton College', division: 'NJCAA', location: 'Fullerton, CA' },
  { name: 'Gavilan College', division: 'NJCAA', location: 'Gilroy, CA' },
  { name: 'Glendale Community College', division: 'NJCAA', location: 'Glendale, CA' },
  { name: 'Golden West College', division: 'NJCAA', location: 'Huntington Beach, CA' },
  { name: 'Grossmont College', division: 'NJCAA', location: 'El Cajon, CA' },
  { name: 'Hartnell College', division: 'NJCAA', location: 'Salinas, CA' },
  { name: 'Imperial Valley College', division: 'NJCAA', location: 'Imperial, CA' },
  { name: 'Irvine Valley College', division: 'NJCAA', location: 'Irvine, CA' },
  { name: 'Lake Tahoe Community College', division: 'NJCAA', location: 'South Lake Tahoe, CA' },
  { name: 'Laney College', division: 'NJCAA', location: 'Oakland, CA' },
  { name: 'Las Positas College', division: 'NJCAA', location: 'Livermore, CA' },
  { name: 'Lassen College', division: 'NJCAA', location: 'Susanville, CA' },
  { name: 'Long Beach City College', division: 'NJCAA', location: 'Long Beach, CA' },
  { name: 'Los Angeles City College', division: 'NJCAA', location: 'Los Angeles, CA' },
  { name: 'Los Angeles Harbor College', division: 'NJCAA', location: 'Wilmington, CA' },
  { name: 'Los Angeles Mission College', division: 'NJCAA', location: 'Sylmar, CA' },
  { name: 'Los Angeles Pierce College', division: 'NJCAA', location: 'Woodland Hills, CA' },
  { name: 'Los Angeles Southwest College', division: 'NJCAA', location: 'Los Angeles, CA' },
  { name: 'Baltimore City Community College', division: 'NJCAA', location: 'Baltimore, MD' },
  { name: 'Miles Community College', division: 'NJCAA', location: 'Miles City, MT' },
];
